server:
  port: 10001

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings,beans
  endpoint:
    health:
      show-details: always

controller:
  endpoints:
    process: '/agent'
    health: '/health'
    readiness: '/readiness'
    liveness: '/liveness'

logging:
  level:
    com:
      alibaba:
        cloud:
          ai:
            graph: DEBUG
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: DEBUG


version: v1
metadata:
  id: optional
  name: "my_assistant"
  description: "An AI assistant for various tasks"
  mode: agent 
  tags:
    - domain: knowledge
    - env: prod
    - owner: saa
